bot_token: 
client_id: 
status_message: 
max_text: 3000
max_images: 5
max_messages: 50
use_plain_responses: true
allow_dms: true
permissions:
  users:
    admin_ids:
    - 
    allowed_ids: []
    blocked_ids:
    - 
  roles:
    allowed_ids: []
    blocked_ids: []
  channels:
    allowed_ids: []
    blocked_ids: []
providers:
  lmstudio:
    base_url: http://localhost:1234/v1
  ollama:
    base_url: http://localhost:11434/v1
models:
  # format is provider/modelIdentifier:      
system_prompt: |
 ""    
